name: Build and Push Docker Image for Requestservice

on:
  push:
    branches:
      - main
    paths:
      - requestservice/**
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Hub authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Maven inside Maven Docker image
        uses: addnab/docker-run-action@v3
        with:
          image: maven:3.9.9-eclipse-temurin-23
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
             cd requestservice && mvn -B clean package

            
      - name: Build Docker image
        run: |
          cd requestservice && docker build -f src/main/docker/Dockerfile.jvm -t alixcja/clubhilfe-requestservice:dev-${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push alixcja/clubhilfe-requestservice:dev-${{ env.TAG }}
